CREATE TABLE IF NOT EXISTS `inventaire` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `NumSerie` varchar(255) NOT NULL,
  `CodeMarque` int(11) DEFAULT NULL,
  `CodeType` int(11) DEFAULT NULL,
  `Model` varchar(255) DEFAULT NULL,
  `CodeUtilisateur` varchar(255) DEFAULT NULL,
  `Dateentree` date DEFAULT NULL,
  `stock` varchar(50) DEFAULT NULL,
  `observation` text,
  `Processeur` varchar(255) DEFAULT NULL,
  `memoire` varchar(255) DEFAULT NULL,
  `disqdur` varchar(255) DEFAULT NULL,
  `graphique` varchar(255) DEFAULT NULL,
  `pouce` varchar(255) DEFAULT NULL,
  `ecran` varchar(255) DEFAULT NULL,
  `mhtz` varchar(255) DEFAULT NULL,
  `mo` varchar(255) DEFAULT NULL,
  `ip` varchar(255) DEFAULT NULL,
  `classification` varchar(255) DEFAULT NULL,
  `STE` varchar(50) DEFAULT NULL,
  `dateinvent` datetime NOT NULL,
  `cause_inventaire` varchar(255) DEFAULT 'Non spécifié',
  PRIMARY KEY (`id`),
  UNIQUE KEY `NumSerie` (`NumSerie`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
